# Generated by Django 4.2.16 on 2024-11-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد')),
                ('type', models.SmallIntegerField(choices=[(1, 'درصد'), (2, 'مقدار ثابت')], default=1, verbose_name='نوع')),
                ('amount', models.PositiveBigIntegerField(verbose_name='درصد / مبلغ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('minimum_spend', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداقل مبلغ سبد خرید')),
                ('maximum_spend', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر مبلغ سبد خرید')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='معتبر تا')),
                ('usage_limit_per_coupon', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت تعداد استفاده')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='products.category', verbose_name='شامل این دسته بندی ها')),
                ('exclude_categories', models.ManyToManyField(blank=True, related_name='exclude_categories', to='products.category', verbose_name='به غیر از این دسته بندی ها')),
                ('exclude_products', models.ManyToManyField(blank=True, related_name='exclude_products', to='products.product', verbose_name='به غیر از این محصولات')),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='products.product', verbose_name='شامل این محصولات')),
            ],
            options={
                'verbose_name': 'کوپن تحفیف',
                'verbose_name_plural': 'کوپن های تخفیف',
            },
        ),
    ]
