# Generated by Django 4.2.16 on 2024-11-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcoupon',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='discountcoupon',
            name='exclude_categories',
        ),
    ]
