# Generated by Django 4.2.16 on 2024-11-10 07:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('enable_gateway', models.BooleanField(default=True, verbose_name='درگاه بانکی فعال باشد')),
                ('enable_transfer', models.BooleanField(default=False, verbose_name='پرداخت کارت به کارت فعال باشد')),
                ('enable_wallet', models.BooleanField(default=True, verbose_name='کیف پول فعال باشد')),
                ('enable_post_paid', models.BooleanField(default=False, verbose_name='پرداخت در محل فعال باشد')),
                ('prepayment_status_for_post_paid', models.BooleanField(default=False, verbose_name='پرداخت بیعانه برای روش پرداخت در محل')),
                ('prepayment_percentage', models.PositiveSmallIntegerField(default=30, help_text='۱ تا ۱۰۰ (درصد بیعانه از جمع کل سفارش کسر می شود.)', verbose_name='درصد بیعانه')),
                ('transfer_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پیکربندی پرداخت',
                'verbose_name_plural': 'پیکربندی پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bank-receipts/%y/%m/%d/', verbose_name='تصویر')),
                ('tracking_code', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='کد رهگیری بانکی')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'در انتظار بررسی'), (2, 'تایید شده'), (3, 'رد شده')], default=1, verbose_name='وضعیت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'رسید',
                'verbose_name_plural': 'رسید ها',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('fullname', models.CharField(max_length=200, verbose_name='نام صاحب حساب')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('bank_logo', models.ImageField(blank=True, null=True, upload_to='bank-logo/', verbose_name='لوگوی بانک')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('shaba', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره حساب')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('payment_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentsetting', verbose_name='پیکربندی')),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت های بانکی',
                'ordering': ('-created',),
            },
        ),
    ]
