# Generated by Django 4.2.16 on 2024-11-10 07:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='محتوا')),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوا')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوا')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('slug_fa', models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('slug_en', models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('page_display_status', models.SmallIntegerField(choices=[(0, 'پیش نویس'), (1, 'انتشار')], default=0, verbose_name='وضعیت نمایش صفحه')),
                ('search_engine_title', models.CharField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_title_fa', models.CharField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_title_en', models.CharField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_description', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_description_fa', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_description_en', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_keywords', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='کلید واژه های موتور جستجو')),
                ('search_engine_keywords_fa', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='کلید واژه های موتور جستجو')),
                ('search_engine_keywords_en', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='کلید واژه های موتور جستجو')),
                ('canonical_link', models.URLField(blank=True, help_text='تگ های کنونیکال به مشکلات محتوای تکراری کمک می کنند.', null=True, verbose_name='لینک کنونیکال')),
                ('canonical_link_fa', models.URLField(blank=True, help_text='تگ های کنونیکال به مشکلات محتوای تکراری کمک می کنند.', null=True, verbose_name='لینک کنونیکال')),
                ('canonical_link_en', models.URLField(blank=True, help_text='تگ های کنونیکال به مشکلات محتوای تکراری کمک می کنند.', null=True, verbose_name='لینک کنونیکال')),
                ('video', models.TextField(blank=True, help_text='کد امبد آپارات یا یوتیوب', null=True, verbose_name='ویدیو صفحه درباره ما')),
            ],
            options={
                'verbose_name': 'درباره',
                'verbose_name_plural': 'درباره',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='محتوا')),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوا')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوا')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('slug_fa', models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('slug_en', models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('page_display_status', models.SmallIntegerField(choices=[(0, 'پیش نویس'), (1, 'انتشار')], default=0, verbose_name='وضعیت نمایش صفحه')),
                ('search_engine_title', models.CharField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_title_fa', models.CharField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_title_en', models.CharField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_description', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_description_fa', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_description_en', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_keywords', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='کلید واژه های موتور جستجو')),
                ('search_engine_keywords_fa', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='کلید واژه های موتور جستجو')),
                ('search_engine_keywords_en', models.TextField(blank=True, help_text='اگر خالی باشد، پیش نمایش آنچه را که به طور خودکار تولید می شود نشان می دهد.', null=True, verbose_name='کلید واژه های موتور جستجو')),
                ('canonical_link', models.URLField(blank=True, help_text='تگ های کنونیکال به مشکلات محتوای تکراری کمک می کنند.', null=True, verbose_name='لینک کنونیکال')),
                ('canonical_link_fa', models.URLField(blank=True, help_text='تگ های کنونیکال به مشکلات محتوای تکراری کمک می کنند.', null=True, verbose_name='لینک کنونیکال')),
                ('canonical_link_en', models.URLField(blank=True, help_text='تگ های کنونیکال به مشکلات محتوای تکراری کمک می کنند.', null=True, verbose_name='لینک کنونیکال')),
                ('video', models.TextField(blank=True, help_text='کد امبد آپارات یا یوتیوب', null=True, verbose_name='ویدیو صفحه اصلی')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
    ]
