# Generated by Django 5.0.1 on 2024-02-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('status', models.CharField(choices=[('Waiting', 'در انتظار'), ('Redirect to bank', 'هدایت شده به بانک'), ('Return from bank', 'بازگشته از بانک'), ('Cancel by user', 'لغو توسط کاربر'), ('Expire gateway token', 'توکن منقضی شده'), ('Expire verify payment', 'تاییدیه پرداخت منقضی شده'), ('Complete', 'تکمیل شده')], max_length=50, verbose_name='وضعیت')),
                ('bank_type', models.CharField(choices=[('BMI', 'ملی'), ('SEP', 'سپه'), ('ZARINPAL', 'زرین پال'), ('IDPAY', 'آیدی پی'), ('ZIBAL', 'زیبال'), ('BAHAMTA', 'باهمتا'), ('MELLAT', 'ملت')], max_length=50, verbose_name='بانک')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='کد پیگیری')),
                ('amount', models.CharField(max_length=10, verbose_name='مبلغ')),
                ('reference_number', models.CharField(max_length=255, unique=True, verbose_name='رفرنس')),
                ('response_result', models.TextField(blank=True, null=True, verbose_name='نتیجه بانک')),
                ('callback_url', models.TextField(verbose_name='آدرس کال بک')),
                ('extra_information', models.TextField(blank=True, null=True, verbose_name='اطلاعات تکمیلی')),
                ('bank_choose_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه بانک انتخابی')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسهٔ شیء')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'order'), ('model', 'order')), models.Q(('app_label', 'wallet'), ('model', 'wallet')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
    ]
