# Generated by Django 4.2.16 on 2024-11-10 07:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('type', models.SmallIntegerField(choices=[(1, 'فرم تماس'), (2, 'پیشنهادات')], verbose_name='نوع')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_checked', models.BooleanField(default=False, verbose_name='بررسی شده؟')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ('-created',),
            },
        ),
    ]
