# Generated by Django 4.2.16 on 2024-11-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('source_language', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=200, verbose_name='زبان مبدا')),
                ('active', models.BooleanField(default=True, help_text='بعد از تغییر لطفا پروژه را ری استارت کنید', verbose_name='فعال')),
                ('search_engine', models.PositiveSmallIntegerField(choices=[(1, 'GoogleTranslator')], default=1, verbose_name='موتور ترجمه')),
            ],
            options={
                'verbose_name': 'تنظیمات مترجم',
                'verbose_name_plural': 'تنظیمات مترجم',
            },
        ),
    ]
