# Generated by Django 4.2.16 on 2024-11-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('name', models.CharField(max_length=255, verbose_name='نام وبسایت')),
                ('name_fa', models.CharField(max_length=255, null=True, verbose_name='نام وبسایت')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='نام وبسایت')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار')),
                ('slogan_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار')),
                ('slogan_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار')),
                ('copyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت')),
                ('copyright_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت')),
                ('copyright_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاوآیکون')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تلفن')),
                ('phone_fa', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تلفن')),
                ('phone_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تلفن')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('address_fa', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('map', models.TextField(blank=True, help_text='کد embed گوگل مپ', null=True, verbose_name='نقشه')),
                ('map_fa', models.TextField(blank=True, help_text='کد embed گوگل مپ', null=True, verbose_name='نقشه')),
                ('map_en', models.TextField(blank=True, help_text='کد embed گوگل مپ', null=True, verbose_name='نقشه')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('zoom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='بزرگنمایی')),
            ],
            options={
                'verbose_name': 'پیکربندی سایت',
                'verbose_name_plural': 'پیکربندی سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('username_or_id', models.CharField(help_text='مثال: firefly@', max_length=100, verbose_name='نام کاربری یا آیدی')),
                ('icon', models.ImageField(upload_to='site/socials/', verbose_name='آیکون')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
