# Generated by Django 4.2.16 on 2024-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteglobalsetting',
            name='xui_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دامنه X-UI'),
        ),
    ]
