# Generated by Django 4.2.16 on 2024-11-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_agent',
            field=models.JSONField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
