# Generated by Django 4.2.16 on 2024-11-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_product_category_and_more'),
        ('coupon', '0002_remove_discountcoupon_categories_and_more'),
        ('article', '0002_alter_articlepost_category'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorygeneralattributes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categorygeneralattributes',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='categorygeneralattributes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='productlistfilter',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productlistfilter',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='productlistfilter',
            name='product_list',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryGeneralAttributes',
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
        migrations.DeleteModel(
            name='ProductListFilter',
        ),
    ]
